### ISSUE TITLE
如何通过wsm执行代码

### ISSUE THREAD

**Issue by Ptkatz** [xiecat/wsm#1]
比如我想要连接哥斯拉shell执行phpinfo()，怎么实现呢

**Comment by Go0p** [comment]
可以参考一下`example`里的例子

https://github.com/xiecat/wsm/blob/main/examples/exec/godzilla/godzilla.go#L63

新年快乐！

**Comment by Ptkatz** [comment]
谢谢师傅，新年快乐

**Comment by Ptkatz** [comment]
师傅可以留个wx吗，方便交流

**Comment by Go0p** [comment]
Go0pzz
